name: pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cycler=0.10.0
  - expat=2.2.5
  - fontconfig=2.13.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - icu=58.2
  - kiwisolver=1.0.1
  - libiconv=1.15
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - pthread-stubs=0.4
  - pyparsing=2.3.1
  - pyqt=5.6.0
  - sip=4.18.1
  - tk=8.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.2
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.6
  - ca-certificates=2019.1.23
  - cairo=1.14.12
  - certifi=2019.3.9
  - cffi=1.12.2
  - cloudpickle=0.8.0
  - cudatoolkit=9.0
  - cytoolz=0.9.0.1
  - dask-core=1.1.4
  - dbus=1.13.2
  - decorator=4.3.2
  - defusedxml=0.5.0
  - entrypoints=0.3
  - ffmpeg=4.0
  - freetype=2.9.1
  - gmp=6.1.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - imageio=2.5.0
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - jasper=2.0.14
  - jedi=0.13.3
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.36
  - libsodium=1.0.16
  - libtiff=4.0.10
  - libvpx=1.7.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.0
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.2
  - ninja=1.8.2
  - notebook=5.7.6
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1b
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.4
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.3
  - pixman=0.38.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pycparser=2.19
  - pygments=2.3.1
  - pyrsistent=0.14.11
  - python=3.7.2
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pywavelets=1.0.2
  - pyzmq=18.0.0
  - qt=5.6.3
  - readline=7.0
  - scikit-image=0.14.2
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.27.2
  - terminado=0.8.1
  - testpath=0.4.2
  - toolz=0.9.0
  - tornado=6.0.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pytorch=1.0.1
  - torchvision=0.2.2
  - pip:
    - dask==1.1.4
    - torch==1.0.1.post2

